AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:

  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
    
  HelloFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: handler.hello
      Runtime: nodejs12.x
      CodeUri: ./hello
      Environment:
        Variables:
          QUEUE_NAME: !Ref MySqsQueue    
      Policies:
        - SQSSendMessagePolicy:
            QueueName:
              !GetAtt MySqsQueue.QueueName
      Events:
        HelloAPI:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /hello
            Method: GET
  
  MySQSQueueFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.queue
      Runtime: nodejs12.x
      Events:
        MySQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt MySqsQueue.Arn
            BatchSize: 1
  
  MySqsQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        ContentBasedDeduplication: true
        QueueName: MyQueue.fifo
        FifoQueue: true
  
Outputs:
  Region:
    Description: "Region"
    Value: !Ref AWS::Region

  ApiId:
    Description: "API ID"
    Value: !Ref MyApi

  ApiUrl:
    Description: "API endpoint URL for Prod environment"
    Value: !Sub 'https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/dev/'